services:
  project_db:
    image: mysql:8.0.17
    volumes:
      - ./db_data:/var/lib/mysql
    restart:
      - always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test_database
      MYSQL_USER: test_user
      MYSQL_PASSWORD: 1234

  redis_db:
    image: redis
    ports:
      - "6380:6379"
    restart: always

  app:
    image: ${IMAGE_STORAGE}/${IMAGE_NAME}:${BUILD_NUMBER}
    container_name: spring-project
    depends_on:
      - project_db
    environment:
      - LANG=ko_KR.UTF-8
      - UWSGI_PORT=8081
    ports:
      - "8081:8080"
networks:
  default:
    external:
      name: service-network